matrix:
  include:
    - language: node_js
      before_install:
        - sudo apt-get install -y gcc-5
      node_js:
        - "8"
    - language: python
      python: 3.6
      before_install:
        - sudo apt-get install -y gcc-5
      install:
        - pip install .
      script:
        - python3 test/python/vrpc_local_test.py

notifications:
  email:
    - burkhard.heisen@xsmail.com
